#!/bin/sh

# -- Create a TAG on git --

RES=$(git show-ref --tags)
if [ -z "$RES" ]; then
    NEW_TAG=1.0.0
else
    NEW_TAG=$(git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}')
fi

git tag -a $NEW_TAG -m "autogenerated tag"
git push origin $NEW_TAG

# -- build docker --

docker build -t laurocesar/sisaih01-downloader DockerfileARM


# -- push to Docker Hub --

# login 

docker login

# tag image
docker tag laurocesar/sisaih01-downloader:latest laurocesar/sisaih01-downloader:$NEW_TAG

# pushing

docker push laurocesar/sisaih01-downloader:$NEW_TAG

exit 0;